#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_DIY_PORT which is usually 8080
#
nohup java -Djetty.host=${OPENSHIFT_DIY_IP} -Djetty.port=${OPENSHIFT_DIY_PORT} -cp ${OPENSHIFT_REPO_DIR}target/dependency/jetty-runner.jar org.eclipse.jetty.runner.Runner --port ${OPENSHIFT_DIY_PORT} --config ${OPENSHIFT_REPO_DIR}src/etc/jetty.xml ${OPENSHIFT_REPO_DIR}/target/thinbus-srp-spring-demo.war > ${OPENSHIFT_LOG_DIR}server.log 2>&1 &
